Update existing cohort parser with warning flag
populationgenomics/metamist pull request #616
Opened 2023-11-19 22:13 UTC by michael-harper

Closes #614 

Added warning flag to log missing data when parsing manifests as opposed to raising a `ValueError`. Also added test case that fails when a `ValueError` is raised and the warning flag is set to `True`.

2023-11-19 22:27 UTC, vivbak commented
Could you resolve the linting and test failures first? Also did you do a test-run of this change?

2023-11-19 22:27 UTC, vivbak requested changes
Could you resolve the linting and test failures first? Also did you do a test-run of this change?

2023-11-20 04:25 UTC, vivbak requested changes
Awesome job! Just a few nits.

2023-11-20 04:25 UTC, vivbak commented on web/package-lock.json
> -    "version": "6.3.0",
Did you intend to bump version here?

2023-11-20 04:25 UTC, vivbak commented on .gitignore
> +venv/
I think we should put this change in a separate PR if we want to add this, it's outside the scope of the change.

2023-11-20 04:25 UTC, vivbak commented on scripts/parse_existing_cohort.py
> +    help='Set this flag to parse manifests with missing data',
Nit, can we be more specific with this comment? i.e. 
```suggestion
    help='Set this flag to parse/ingest sequencing groups with missing reads',
```

2023-11-20 04:25 UTC, vivbak commented on test/test_parse_existing_cohort.py
> +        """Test when allow_missing_files is False and records with missing fastqs, ValueError is raised"""
Nit, readability. 
```suggestion
        """Test ValueError is raised when allow_missing_files is False and sequencing groups have no reads"""
```

2023-11-20 04:25 UTC, vivbak commented on test/test_parse_existing_cohort.py
> +    async def test_get_read_filenames_no_reads_pass(self):
Could we also test that a warning is raised?

2023-11-20 05:17 UTC, michael-harper commented on web/package-lock.json
> -    "version": "6.3.0",
I did not, what version should it be?

2023-11-20 07:27 UTC, vivbak approved these changes
Great job! We need a release for this to work. I'll action now.

2023-11-20 07:28 UTC, merged